import modelController from './model.js';


let UIController = (() => {

    let DOM = {
        container: '#graph',
		addNew: '#add-new',
		addNewModalForm: '#add-new-modal form',
		points: 'foreignObject .link-points',
		linkPointsClass: '.link-points',
		linkPoints: 'link-points',
		topPoint: 'top-point', // without "."
		rightPoint: 'right-point',
		bottomPoint: 'bottom-point',
		leftPoint: 'left-point'
    };



    function buildItemList(){
        console.log("buildItemList")
    }


	function drawTree(){
		console.log("Draw tree")

		dTree.init(modelController.storage.getData(), {
			target: DOM.container,
			debug: true,
			height: $( window ).height() - 20,
			width: $( window ).width(),

			callbacks: {
				// nodeSize: function(width, height){
				// 	console.log("------------")
				// 	console.log(width)
				// 	console.log(height)
				// },

				// nodeSize: function(nodes, width, textRenderer){
				// 	return [120,70] ;
				// },

			  nodeClick: function(name, extra) {

				  let target = $(d3.event.target);
				  let id = target.closest('foreignObject > div > div').attr('id'); 	//this.id;  ID from data object, not generated by dTree
				  if($(target[0]).hasClass(DOM.linkPoints)){
					  modelController.pointsHandler($(target[0]), id);				// Click on point
				  }else{
					  modelController.selectNode(id); 								// Click on Node
				  }

			  },


				textRenderer: function(name, extra, textClass) {
				  let photo;
				  let datesBlock = '';
				  let nodeId = '';

				  if(extra && extra.nodeId){
					  nodeId = extra.nodeId;
				  }
				  if (extra && extra.maidenName){
					  name = name + " (" + extra.maidenName + ")";
				  }
				  if (extra && extra.photoLink){
					  photo = `<img src="${extra.photoLink}" />`;
				  }	else {
					  photo = `<img src="img/result-user-avatar.png" />`;
				  }
				  if(extra && extra.dates){
					  datesBlock = `<p class="dates">${extra.dates}</p>`;
				  }

				  return `
					<div id="${nodeId}">
						<div class="photo">${photo}</div>
						<div>
							<p class="${textClass}">${name}</p>
							${datesBlock}
						</div>
						<div class="link-points ${DOM.topPoint}">Parent</div>
						<div class="link-points ${DOM.rightPoint}">Spouse</div>
						<div class="link-points ${DOM.bottomPoint}">Child</div>
						<div class="link-points ${DOM.leftPoint}"></div>
					</div>
					`;
			  }
			},
			nodeWidth: 200
		});
		console.log("Tree is built")
	}


    return {
		buildItemList: buildItemList,
		drawTree: drawTree,
        DOM: function(){
            return DOM;
        }
    };

})();
export default UIController;